[2023-12-21T07:25:36.531+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag.process_data manual__2023-12-21T07:21:12.241440+00:00 [queued]>
[2023-12-21T07:25:36.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag.process_data manual__2023-12-21T07:21:12.241440+00:00 [queued]>
[2023-12-21T07:25:36.536+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-12-21T07:25:36.543+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_data> on 2023-12-21 07:21:12.241440+00:00
[2023-12-21T07:25:36.546+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2023-12-21T07:25:36.549+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_dag', 'process_data', 'manual__2023-12-21T07:21:12.241440+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmprvkgnudg']
[2023-12-21T07:25:36.549+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask process_data
[2023-12-21T07:25:36.576+0000] {task_command.py:416} INFO - Running <TaskInstance: example_dag.process_data manual__2023-12-21T07:21:12.241440+00:00 [running]> on host a4cbb2176d38
[2023-12-21T07:25:36.629+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='niko' AIRFLOW_CTX_DAG_ID='example_dag' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T07:21:12.241440+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T07:21:12.241440+00:00'
[2023-12-21T07:25:36.630+0000] {first.py:70} ERROR - Error in processing data: string indices must be integers
[2023-12-21T07:25:36.635+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/first.py", line 66, in process_data
    processed_data = [task for task in data if task["completed"]]
  File "/opt/airflow/dags/first.py", line 66, in <listcomp>
    processed_data = [task for task in data if task["completed"]]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first.py", line 71, in process_data
    raise AirflowException(f"Error in processing data: {e}")
airflow.exceptions.AirflowException: Error in processing data: string indices must be integers
[2023-12-21T07:25:36.637+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=example_dag, task_id=process_data, execution_date=20231221T072112, start_date=20231221T072536, end_date=20231221T072536
[2023-12-21T07:25:36.643+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 105 for task process_data (Error in processing data: string indices must be integers; 107)
[2023-12-21T07:25:36.689+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T07:25:36.704+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
